# Generated by Django 4.0.5 on 2022-07-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_task_user_task_account_task_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='account',
            new_name='user',
        ),
    ]
