# Generated by Django 4.0.5 on 2022-07-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_account_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
