# Generated by Django 4.0.5 on 2022-07-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='account',
            new_name='user',
        ),
    ]
