# Generated by Django 4.0.5 on 2022-08-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_rename_account_folder_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='name',
            new_name='folder_name',
        ),
    ]
