# Generated by Django 4.0.5 on 2022-11-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_rename_name_folder_folder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='color',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
